In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [6]:
import time

a = np.random.random(1000000)
b = np.random.random(1000000)

tic = time.time()
m = np.dot(a, b)
toc = time.time()

print("Vectorized: " + str((toc-tic)*1000) + "ms")

tic = time.time()
m2 = 0
for i in range(1000000):
    m2 += a[i]*b[1]
toc = time.time()

print("For loop: " + str((toc-tic)*1000) + "ms")

Vectorized: 0.5011558532714844ms
For loop: 567.1179294586182ms


In [17]:
# matrices.
A = np.matrix([[1, 5, 3], [-5, 8, 1]])
b = np.matrix([[1], [-1], [0]])
print(A)
print(b.shape)

[[ 1  5  3]
 [-5  8  1]]
(3, 1)


In [18]:
m = np.dot(A, b)
m.shape

(2, 1)

In [13]:
A.shape

(2, 3)

In [19]:
A.T

matrix([[ 1, -5],
        [ 5,  8],
        [ 3,  1]])

In [23]:
# can define matrices also with arrays.
A = np.array([[1, 5, 3], [-5, 8, 1]])
b = np.array([[1], [-1], [0]])
np.dot(A, b)

array([[ -4],
       [-13]])

In [29]:
# broadcasting.
A = np.array([[56, 0, 4.4, 68], [1.2, 104, 52, 8], [1.8, 135, 99, 0.9]])
(np.sum(A, axis = 0)).reshape(1, 4)

array([[  59. ,  239. ,  155.4,   76.9]])